
const format = (bookings = []) => bookings.map(
    ({
      bookings,
      brands,
      channels,
      listings,
      view,
      charges,
      json_charges: jsonCharges,
      refunds,
      customer,
      guest_contact: guestContact,
      listing,
      organization,
      current_employee_role: currentEmployeeRole,
      stripe_publishable_key: stripePublishableKey,
      booking,
      booking_channel_logo: bookingChannelLogo,
      booking_chanel_name: bookingChannelName,
      stripe_account_id: stripeAccountId,
      deposits,
      price_status: priceStatus,
      cancelled_refund_status: cancelledRefundStatus,
      unit,
      property,
      location,
      security_deposit_collected: securityDepositCollected,
      work_orders: workOrders,
      quote,
      room_rate: roomRate,
      special_guest_fee_rate: specialGuestFeeRate,
      special_guest_fee_amount: specialGuestFeeAmount,
      management_fee_rate: managementFeeRate,
      management_fee_amount: managementFeeAmount,
      total_management_fees: totalManagementFees,
      fees,
      fees_total: feesTotal,
      property_owner_net: propertyOwnerNet,
      property_owner_rate: propertyOwnerRate,
      house_keeping_rate: houseKeepingRate,
      hose_keeping_net: houseKeepingNet,
      channel_inflator_amount: channelInflatorAmount,
      channel_inflator_rate: channelInflatorRate,
      channel_fee_amount: channelFeeAmount,
      channel_fee_rate: channelFeeRate,
      organization_net: organizationNet,
      avg_room_rate: avgRoomRate,
      billable_range: billableRange,
      los_discount_type: losDiscountType,
      los_discount_rate: losDiscountRate,
      los_discount_amount: losDiscountAmount,
      tax_rate: taxRate,
      tax_amount: taxAmount,
      booking_total: bookingTotal,
      direct_fee: directFee,
      direct_fee_rate: directFeeRate,
      total_system_fees: totalSystemFees,
      stripe_fee: stripeFee,
      stripe_payout: stripePayout,
      total_payout: totalPayout,
      property_owner_subtotal: propertyOwnerSubtotal,
      net_before_fees: netBeforeFees,
      source,
      booking_net_detail: bookingNetDetail,
      loading
    }) => ({
      bookings,
      brands,
      channels,
      listings,
      view,
      charges,
      jsonCharges,
      refunds,
      customer,
      guestContact,
      listing,
      organization,
      currentEmployeeRole,
      stripePublishableKey,
      booking,
      bookingChannelLogo,
      bookingChannelName,
      stripeAccountId,
      deposits,
      priceStatus,
      cancelledRefundStatus,
      unit,
      property,
      location,
      securityDepositCollected,
      workOrders,
      quote,
      roomRate,
      specialGuestFeeAmount,
      specialGuestFeeRate,
      managementFeeRate,
      managementFeeAmount,
      totalManagementFees,
      fees,
      feesTotal,
      propertyOwnerNet,
      propertyOwnerRate,
      houseKeepingNet,
      houseKeepingRate,
      channelInflatorAmount,
      channelInflatorRate,
      channelFeeAmount,
      channelFeeRate,
      organizationNet,
      avgRoomRate,
      billableRange,
      losDiscountType,
      losDiscountRate,
      losDiscountAmount,
      taxRate,
      taxAmount,
      bookingTotal,
      directFee,
      directFeeRate,
      totalSystemFees,
      stripeFee,
      stripePayout,
      totalPayout,
      propertyOwnerSubtotal,
      netBeforeFees,
      source,
      bookingNetDetail,
      loading
    })
)

export const getBookings = async(client, organizationId: number, bookingCode: string) => {

    const { bookings = []} = await client.get(`https://app.getdirect.io/api/${organizationId}/bookings/${bookingCode}`).json()

    return format(bookings)
}