

const formatOne = ({
    id,
    name,
    active,
    multi_unit: multiUnit,
    summary_accommodations: summaryAccommodations,
    summary_description: summaryDescription,
    summary_headline: summaryHeadline,
    summary_rules: summaryRules,
    features_adventure: featuresAdventure,
    features_attractions: featuresAttractions,
    features_car: featuresCar,
    features_leisure: featuresLeisure,
    features_local: featuresLocal,
    features_location: featuresLocation,
    property_type:  propertyType,
    organization_id: organizationId,
    created_at: createdAt,
    updated_at: updatedAt,
    manager_info_visible: managerInfoVisible,
    registration_id: registrationId,
    external_id: externalId,
    extra,
    location,
    images_property: imagesProperty,
    attached_files: attachedFiles,
    distribution_required_amenities: distributionRequiredAmenities,
    is_incomplete: isIncomplete,
    bookings,
    bookings_upcomingL: bookingsUpcoming,
    bookings_with_unpaid: bookingsWithUnpaid,
    brands,
    google_maps_api_key: googleMapsApiKey,
    incomplete_properties: incompleteProperties,
    listings,
    default_listing: defaultListing,
    notifications,
    pages,
    Property_count: PropertyCount,
    properties,
    recent_bookings: recentBookings,
    stripe_connect_account: stripeConnectAccount,
    stripe_connect_key: stripeConnectKey,
    units,
    bathrooms,
    bedrooms,
    features_accommodations: featuresAccommodations,
    features_amenities: featuresAmenities,
    features_dining: featuresDining,
    features_entertainment: featuresEntertainment,
    features_outdoor: featuresOutdoor,
    features_spa:  featuresSpa,
    features_suitability: featuresSuitability,
    features_themes: featuresThemes,
    images_unit: imagesUnit,
    available_30_days: available30Days,
    unit_availability: unitAvailability,
    availability_calendar: availabilityCalendar,
    default_uvailability_changeover: defaultAvailabilityChangeover,
    unlisted_brands: unlistedBrands

}) => ({

    id,
    name,
    active,
    multiUnit,
    summaryAccommodations,
    summaryDescription,
    summaryHeadline,
    summaryRules,
    featuresAdventure,
    featuresAttractions,
    featuresCar,
    featuresLeisure,
    featuresLocal,
    featuresLocation,
    propertyType,
    organizationId,
    createdAt,
    updatedAt,
    managerInfoVisible,
    registrationId,
    externalId,
    extra,
    location,
    imagesProperty,
    attachedFiles,
    distributionRequiredAmenities,
    isIncomplete,
    bookings,
    bookingsUpcoming,
    bookingsWithUnpaid,
    brands,
    googleMapsApiKey,
    incompleteProperties,
    listings,
    defaultListing,
    notifications,
    pages,
    PropertyCount,
    properties,
    recentBookings,
    stripeConnectAccount,
    stripeConnectKey,
    units,
    bathrooms,
    bedrooms,
    featuresAccommodations,
    featuresAmenities,
    featuresDining,
    featuresEntertainment,
    featuresOutdoor,
    featuresSpa,
    featuresSuitability,
    featuresThemes,
    imagesUnit,
    available30Days,
    unitAvailability,
    availabilityCalendar,
    defaultAvailabilityChangeover,
    unlistedBrands,
})

// // When I last coded on this I changed it to Property from Properties because I belive the data comes back as a big 
// // object however the .get works fine in post man when you send it in GraphQl you get back a Search Results
// Web results422 Unprocessable Entity witch means that the server undestands 
// // the rtequest and may even be sending it but the data is not comming back the way it is expected to look witch in my mind 
// // means I have not mapped it correctly so hopefully youll be able to re format the type and format it correctly.

export const getProperty = async (client, organizationId: number, id: number) => {
    const {property = []} = await client.get(`https://app.getdirect.io/api/${organizationId}/properties/${id}`).json()
    console.log(property)
  
    return formatOne(property)
  }
  
 